### ISSUE TITLE
Back to singleline.

### ISSUE THREAD

**Issue by captify-iolenchenko** [bhml/atom-multiline-bracket#1]
Hi,
started to use this package (very useful so far) but I feel lack of `back to single line` functionality, I mean transform multiline back to singleline. Just the same keybindings. Did you consider have this in your package?

Actually i can help with that if you don't have time on it.

Thanks.

**Comment by bhml** [comment]
Hi Illia,

I have considered to implement the ability to toggle the transformation for this plugin, but I realise this could easily be achieved/reverted by using Atom's core join line method: <kbd>cmd + j</kbd>, and then removing the trailing comma.

What are you thoughts?

**Comment by captify-iolenchenko** [comment]
oh, really i didn't know about this also, works just as i expected. Don't think it worth to duplicate logic in package. Thanks!

Closing issue.
